# source("src/NYCF_housekeeping_GIS_vars.R")

### Prepare summary NYC table for paper

data_NYC <- read_csv("data/3_output/stormwater_analysis_final_database.csv") %>%
  filter(Geography == "NYC")

df_summary_NYC <- data.frame(category = c("Area Flooded (sqkm)",
                                          "Population",
                                          "Road area (sqkm)", 
                                          "Bus stops", 
                                          "Bus routes",
                                          "Subway entrances",
                                          "Residential lots affected without a basement",
                                          "Residential lots with a basement",
                                          "Mixed Commercial and Residential Lots",
                                          "Commercial Lots",
                                          "Industrial Lots",
                                          "Black, Indigenous, People of Color (BIPOC)",
                                          "Children population",
                                          "Elderly population",
                                          "Poverty",
                                          "Low Income Households",
                                          "Households with one or more residents with a disability",
                                          "Rent Burdened Households",
                                          "Costs Burdened Households"),
                             M.absolute = c(data_NYC$M.Total_area/1000000,
                                            data_NYC$M.Total_population,
                                            data_NYC$M.Total_road_area/1000000,
                                            data_NYC$M.Total_bus_stops,
                                            data_NYC$M.Total_bus_routes,
                                            data_NYC$M.Total_subway_stops,
                                            data_NYC$M.Total_residential_lots,
                                            data_NYC$M.Total_basement_residential_lots,
                                            data_NYC$M.Total_mixed_comres_lots,
                                            data_NYC$M.Total_commercial_lots,
                                            data_NYC$M.Total_industrial_lots,
                                            data_NYC$M.Total_bipoc_population,
                                            data_NYC$M.Total_below5_population,
                                            data_NYC$M.Total_above65_population,
                                            data_NYC$M.Total_Belpov_e,
                                            data_NYC$M.HH_Income_Bel75K_e,
                                            data_NYC$M.HH_Disability_e,
                                            data_NYC$M.RB_HH_e,
                                            data_NYC$M.CB_HH_e),
                             M.pct = c(data_NYC$M.PCT_area,
                                       data_NYC$M.PCT_Total_population,
                                       data_NYC$M.PCT_road_area,
                                       data_NYC$M.PCT_bus_stops,
                                       data_NYC$M.PCT_bus_routes,
                                       data_NYC$M.PCT_subway_stops,
                                       data_NYC$M.PCT_residential_lots,
                                       data_NYC$M.PCT_basement_residential_lots,
                                       data_NYC$M.PCT_mixed_comres_lots,
                                       data_NYC$M.PCT_commercial_lots,
                                       data_NYC$M.PCT_industrial_lots,
                                       data_NYC$M.PCT_bipoc_population,
                                       data_NYC$M.PCT_below5_population,
                                       data_NYC$M.PCT_above65_population,
                                       data_NYC$M.PCT_Belpov_e,
                                       data_NYC$M.PCT_HH_Income_Bel75K_e,
                                       data_NYC$M.PCT_Disability_e,
                                       data_NYC$M.PCT_RB_e,
                                       data_NYC$M.PCT_CB_e),
                             E.absolute = c(data_NYC$E.Total_area/1000000,
                                            data_NYC$E.Total_population,
                                            data_NYC$E.Total_road_area/1000000,
                                            data_NYC$E.Total_bus_stops,
                                            data_NYC$E.Total_bus_routes,
                                            data_NYC$E.Total_subway_stops,
                                            data_NYC$E.Total_residential_lots,
                                            data_NYC$E.Total_basement_residential_lots,
                                            data_NYC$E.Total_mixed_comres_lots,
                                            data_NYC$E.Total_commercial_lots,
                                            data_NYC$E.Total_industrial_lots,
                                            data_NYC$E.Total_bipoc_population,
                                            data_NYC$E.Total_below5_population,
                                            data_NYC$E.Total_above65_population,
                                            data_NYC$E.Total_Belpov_e,
                                            data_NYC$E.HH_Income_Bel75K_e,
                                            data_NYC$E.HH_Disability_e,
                                            data_NYC$E.RB_HH_e,
                                            data_NYC$E.CB_HH_e),
                             E.pct = c(data_NYC$E.PCT_area,
                                       data_NYC$E.PCT_Total_population,
                                       data_NYC$E.PCT_road_area,
                                       data_NYC$E.PCT_bus_stops,
                                       data_NYC$E.PCT_bus_routes,
                                       data_NYC$E.PCT_subway_stops,
                                       data_NYC$E.PCT_residential_lots,
                                       data_NYC$E.PCT_basement_residential_lots,
                                       data_NYC$E.PCT_mixed_comres_lots,
                                       data_NYC$E.PCT_commercial_lots,
                                       data_NYC$E.PCT_industrial_lots,
                                       data_NYC$E.PCT_bipoc_population,
                                       data_NYC$E.PCT_below5_population,
                                       data_NYC$E.PCT_above65_population,
                                       data_NYC$E.PCT_Belpov_e,
                                       data_NYC$E.PCT_HH_Income_Bel75K_e,
                                       data_NYC$E.PCT_Disability_e,
                                       data_NYC$E.PCT_RB_e,
                                       data_NYC$E.PCT_CB_e),
                             citywide.absolute = c(data_NYC$Total_area/1000000,
                                                   data_NYC$Total_population,
                                                   data_NYC$Total_road_area/1000000,
                                                   data_NYC$Total_bus_stops,
                                                   data_NYC$Total_bus_routes,
                                                   data_NYC$Total_subway_stops,
                                                   data_NYC$Total_residential_lots,
                                                   data_NYC$Total_basement_residential_lots,
                                                   data_NYC$Total_mixed_comres_lots,
                                                   data_NYC$Total_commercial_lots,
                                                   data_NYC$Total_industrial_lots,
                                                   data_NYC$Total_bipoc_population,
                                                   data_NYC$Total_below5_population,
                                                   data_NYC$Total_above65_population,
                                                   data_NYC$Total_Belpov_e,
                                                   data_NYC$HH_Income_Bel75K_e,
                                                   data_NYC$HH_Disability_e,
                                                   data_NYC$RB_HH_e,
                                                   data_NYC$CB_HH_e),
                             citywide.pct = c(100,
                                              100,
                                              100,
                                              100,
                                              100,
                                              100,
                                              100,
                                              100,
                                              100,
                                              100,
                                              100,
                                              data_NYC$PCT_bipoc_population,
                                              data_NYC$PCT_below5_population,
                                              data_NYC$PCT_above65_population,
                                              data_NYC$PCT_Belpov_e,
                                              data_NYC$PCT_HH_Income_Bel75K_e,
                                              data_NYC$PCT_Disability_e,
                                              data_NYC$PCT_RB_e,
                                              data_NYC$PCT_CB_e))

write.csv(df_summary_NYC,
          row.names = FALSE,
          "data/3_output/stormwater_analysis_final_NYC_summary.csv")
